### ISSUE TITLE
Is the final result on leadingboard trained using train and val dataset both?

### ISSUE THREAD

**Issue by shouldnotfail** [decisionforce/mmTransformer#1]
Hi! I always wonder know, if the models with competitive results use train dataset only?  Because when I tried to submit the result using train and validation dataset, there was a drop in performance. :(

**Comment by jzhang538** [comment]
Hi, I think the models trained with more data typically have better performances. At least in our experiments (we also compare models trained with train and validation set), they possess higher accuracy in ADE, FDE and MR. I think this phenomenon can be widely observed in data-driven models.

**Comment by jzhang538** [comment]
> Hi! I always wonder know, if the models with competitive results use train dataset only? Because when I tried to submit the result using train and validation dataset, there was a drop in performance. :(

Hi, I think the models trained with more data typically have better performances. At least in our experiments (we also compare models trained with train and validation set), they possess higher accuracy in ADE, FDE and MR. I think this phenomenon can be widely observed in data-driven models.
