### ISSUE TITLE
'map.pkl'文件为Python3.8情况下保存的

### ISSUE THREAD

**Issue by Gengmaosi** [decisionforce/mmTransformer#11]
如题，在执行'val_dataset = ArgoverseDataset(validation_cfg)'命令时，出现'ValueError: unsupported pickle protocol: 5'问题，应该是pickle储存文件时Python版本问题，但您在code解释部分，要求开发环境保持为Python3.7。

**Comment by Mrmoore98** [comment]
Thanks for pointing out this issue, we will fix it. We have provided code for generating 'map.pkl' from scratch. You can use that code.

**Comment by jzhang538** [comment]
> 如题，在执行'val_dataset = ArgoverseDataset(validation_cfg)'命令时，出现'ValueError: unsupported pickle protocol: 5'问题，应该是pickle储存文件时Python版本问题，但您在code解释部分，要求开发环境保持为Python3.7。

Download map.pkl for python 3.7 with this link https://drive.google.com/file/d/1HbsgutM1PKjPj-3IIA5kG3mJEMhHGhS0/view
