### ISSUE TITLE
训练过程代码

### ISSUE THREAD

**Issue by Gengmaosi** [decisionforce/mmTransformer#12]
作者您好，在学习您开源的代码过程中，我并没有找到模型训练过程的代码。请问模型训练部分的代码您开源了吗？如果开源了的话，能否指明训练代码的具体位置呢？

**Comment by DinghaoXi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到邮件，会尽快给您回复。by小溪

**Comment by Mrmoore98** [comment]
This repo is official implementation for mmTransformer in pytorch. Currently, the core code of mmTransformer is implemented in the commercial project, we provide inference code of model with six trajectory propopals for your reference.
