### ISSUE TITLE
argoverse_info_val.pkl for Python 3.7

### ISSUE THREAD

**Issue by wangqf1997** [decisionforce/mmTransformer#19]
Hello,

For Python 3.7, You only provide 'map.pkl', but we also need 'argoverse_info_val.pkl'. Can you add it？

Thanks!

**Comment by DinghaoXi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到邮件，会尽快给您回复。by小溪

**Comment by DinghaoXi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到邮件，会尽快给您回复。by小溪
