### ISSUE TITLE
Could you provide your training log?

### ISSUE THREAD

**Issue by TimHo0331** [decisionforce/mmTransformer#2]
It is said that the code would be relased at April, but there is still nothing.......
Looking forward to the source code.
Thank you!

**Comment by jzhang538** [comment]
> It is said that the code would be relased at April, but there is still nothing.......
> Looking forward to the source code.
> Thank you!

Sorry for the delay since the code is still waiting for the internal approval. If you have any problem with reproduction, you can send an email with specific issue to us. We will try our best to help you.
