### ISSUE TITLE
details about the embedding dimension

### ISSUE THREAD

**Issue by Yisten** [decisionforce/mmTransformer#3]
Could you provide the the embedding dimension of each step in motion aggregator and map extractor( with VectorNet)? I haven't found them or correponding reference in Implementation Details in Appendix. Are they same with the hidden state(128)?

**Comment by Yisten** [comment]
Additionally, could you tell more about the comsumption of the graphic memory when doing inference? It will help me a lot.

**Comment by Mrmoore98** [comment]
> Could you provide the the embedding dimension of each step in motion aggregator and map extractor( with VectorNet)? I haven't found them or correponding reference in Implementation Details in Appendix. Are they same with the hidden state(128)?

Yes, all the hidden feature have the same dimensional size(128)
And the implementation of VectorNet you can refer to this [repo](https://github.com/xk-huang/yet-another-vectornet). We use the vector net to encode each lane vector set into a 128-dimensional vector.

**Comment by Mrmoore98** [comment]
> Additionally, could you tell more about the comsumption of the graphic memory when doing inference? It will help me a lot.

In my implementation, the comsumption of the GPU at inference stage is 3998MiB when the batchsize is 64. I use GTX 1660 to get this result.

**Comment by Yisten** [comment]
Thanks for your reply and it is very informative!
One more question about initialization, please.
Is Xaiver enough? Had you pretrained the vectornet before compound training? If yes, how?

**Comment by Mrmoore98** [comment]
> Thanks for your reply and it is very informative!
> One more question about initialization, please.
> Is Xaiver enough? Had you pretrained the vectornet before compound training? If yes, how?

All the componets in mmTransformer are trained from scratch. You can try different initialization methods. This initialization method is inherited from the aforementioned repo. 

FYI, all the weights are initialized with Xaiver, except for the trajectory proposals, which are initialized with orthogonalize initilization.

**Comment by Yisten** [comment]
Got it! Thanks for your patience and have a nice day XD

**Comment by Mrmoore98** [comment]
If you have further problems about reproduction, feel free to open a new issue.
