### ISSUE TITLE
Some questions about visulization 

### ISSUE THREAD

**Issue by lyk1993** [decisionforce/mmTransformer#6]
Hi, many thanks for the quick replies on other issues and sharing the data preprocessing repo. I have some questions about the visualization part.

1. The demo video looks really impressive, but I think for the argoverse forecasting data, the total length is only 5 seconds. In the demo video, each scene looks like lasts about 30 seconds. So I'm wondering if you are using the argoverse forecasting data for visualization?

2. For the argo data I think it is relatively easy to get and visualize the map with the help of API, but the forecasting data itself did not provide information regarding bounding box size, orientation, etc. So how do you get that information for visualization?

3. I saw that the core code is implemented in the commercial project so it may difficult to release to the public, but I'm wondering if it is possible to release the code for visualization?

Many thanks!

**Comment by shouldnotfail** [comment]
the visualization should be done on the argoverse dataset with tracking label, that means you have to clean the tracking dataset by yourself and then reconstruct the data into agroverse forecasting from.

**Comment by jzhang538** [comment]
> Hi, many thanks for the quick replies on other issues and sharing the data preprocessing repo. I have some questions about the visualization part.
> 
> 1. The demo video looks really impressive, but I think for the argoverse forecasting data, the total length is only 5 seconds. In the demo video, each scene looks like lasts about 30 seconds. So I'm wondering if you are using the argoverse forecasting data for visualization?
> 2. For the argo data I think it is relatively easy to get and visualize the map with the help of API, but the forecasting data itself did not provide information regarding bounding box size, orientation, etc. So how do you get that information for visualization?
> 3. I saw that the core code is implemented in the commercial project so it may difficult to release to the public, but I'm wondering if it is possible to release the code for visualization?
> 
> Many thanks!

We use Argoverse Tracking dataset to do visualization. You can have access to all the additional information such as bbox and orientation with that. We will release the visualization code later. Stay tunned!

**Comment by lyk1993** [comment]
> > Hi, many thanks for the quick replies on other issues and sharing the data preprocessing repo. I have some questions about the visualization part.
> > 
> > 1. The demo video looks really impressive, but I think for the argoverse forecasting data, the total length is only 5 seconds. In the demo video, each scene looks like lasts about 30 seconds. So I'm wondering if you are using the argoverse forecasting data for visualization?
> > 2. For the argo data I think it is relatively easy to get and visualize the map with the help of API, but the forecasting data itself did not provide information regarding bounding box size, orientation, etc. So how do you get that information for visualization?
> > 3. I saw that the core code is implemented in the commercial project so it may difficult to release to the public, but I'm wondering if it is possible to release the code for visualization?
> > 
> > Many thanks!
> 
> We use Argoverse Tracking dataset to do visualization. You can have access to all the additional information such as bbox and orientation with that. We will release the visualization code later. Stay tunned!

Thank you all for the response. I will close this one and looking forward to seeing the visualization code, thanks!

**Comment by MasterIzumi** [comment]
@jzhang538 Hi, have you re-trained the network on the re-organized tracking dataset? Or just use it for visualization?
